//
//  LanguageMapper.swift
//  LocalizeWiz
//
//  Created by John Warmann on 2020-06-01.
//  Copyright © 2020 LocalizeWiz. All rights reserved.
//

import Foundation

class LanguageMapper {

    private var languageMap: [String: String] = [
        "ab": "ab",
        "ach": "ach",
        "af": "af",
        "af-za": "af",
        "am": "am",
        "an": "an",
        "ar": "ar",
        "ar-":"ar",
        "ar-ae":"ar",
        "ar-ar":"ar",
        "ar-dz":"ar",
        "ar-eg":"ar",
        "ar-es":"ar",
        "ar-il":"ar",
        "ar-iq":"ar",
        "ar-jo":"ar",
        "ar-kw":"ar",
        "ar-lb":"ar",
        "ar-ly":"ar",
        "ar-ma":"ar",
        "ar-mr":"ar",
        "ar-om":"ar",
        "ar-ps":"ar",
        "ar-qa":"ar",
        "ar-sa":"ar",
        "ar-sy":"ar",
        "ar-ye":"ar",
        "ast": "ast",
        "au-at": "au",
        "ay": "ay",
        "az": "az",
        "az-az": "az",
        "az-latn-az": "az",
        "ba": "ba",
        "be": "be",
        "be-by": "be",
        "bg": "bg",
        "bg-bg": "bg",
        "bg-en": "bg",
        "bn": "bn",
        "bn-bd": "bn",
        "bn-in": "bn",
        "bo": "bo",
        "br": "br",
        "bs": "bs",
        "bs-ba": "bs",
        "bs-latn-ba": "bs",
        "by": "by",
        "ca": "ca",
        "ca-ad": "ca",
        "ca-es": "ca",
        "ch":  "ch",
        "cs": "cs",
        "cs-cz": "cs",
        "cy": "cy",
        "cy-gb": "cy",
        "cz": "cz",
        "cz-cz": "cz",
        "cz-en": "cz",
        "cz-us": "cz",
        "da": "da",
        "da-dk": "da",
        "da-gl": "da",
        "danish-denmark": "da",
        "de": "de",
        "de_de": "de",
        "de-at": "de",
        "de-ch": "de",
        "de-de": "de",
        "de-en": "de",
        "de-li": "de",
        "dutch-netherlands": "nl",
        "el": "el",
        "el-gr": "el",
        "en":  "en",
        "en_ca": "en",
        "en_gb": "en",
        "en_us": "en",
        "en-": "en",
        "en-001": "en",
        "en-029": "en",
        "en-150": "en",
        "en-ae": "en",
        "en-at": "en",
        "en-au": "en",
        "en-be": "en",
        "en-bg": "en",
        "en-br": "en",
        "en-ca": "en",
        "en-ch": "en",
        "en-cn": "en",
        "en-cy": "en",
        "en-de": "en",
        "en-dk": "en",
        "en-eg": "en",
        "en-en": "en",
        "en-es": "en",
        "en-fi": "en",
        "en-gb": "en",
        "en-gb-en-gb": "en",
        "en-gb.utf-8": "en",
        "en-gb.utf8": "en",
        "en-gr": "en",
        "en-gu": "en",
        "en-he": "en",
        "en-hk": "en",
        "en-hu": "en",
        "en-id": "en",
        "en-ie": "en",
        "en-il": "en",
        "en-in": "en",
        "en-jm": "en",
        "en-jo": "en",
        "en-ke": "en",
        "en-lr": "en",
        "en-mt": "en",
        "en-mx": "en",
        "en-my": "en",
        "en-na": "en",
        "en-new": "en",
        "en-nl": "en",
        "en-nz": "en",
        "en-ph": "en",
        "en-pk": "en",
        "en-pl": "en",
        "en-qa": "en",
        "en-ru": "en",
        "en-sd": "en",
        "en-se": "en",
        "en-sg": "en",
        "en-si": "en",
        "en-sk": "en",
        "en-th": "en",
        "en-tr": "en",
        "en-tt": "en",
        "en-tur": "en",
        "en-ua": "en",
        "en-ug": "en",
        "en-uk": "en",
        "en-us": "en",
        "en-us-en-us": "en",
        "en-us,de-de": "en",
        "en-us,en;q=0.5-en-us,en;q=0.5": "en",
        "en-us;q=0.5": "en",
        "en-us;q=1.0": "en",
        "en-us.": "en",
        "en-us.utf-8": "en",
        "en-us.utf8": "en",
        "en-vg": "en",
        "en-vn": "en",
        "en-ws": "en",
        "en-xa": "en",
        "en-za": "en",
        "en-zw": "en",
        "en;q=0.8;ru;q=0.5": "en",
        "en;q=1.0": "en",
        "en/": "en",
        "english": "en",
        "english-united-states": "en",
        "english(en)": "en",
        "eo": "eo",
        "eo-xx": "eo",
        "es": "es",
        "es_mx": "es",
        "es_us": "es",
        "es-": "es",
        "es-419": "es",
        "es-ar": "es",
        "es-bo": "es",
        "es-br": "es",
        "es-cl": "es",
        "es-co": "es",
        "es-cr": "es",
        "es-do": "es",
        "es-ec": "es",
        "es-es": "es",
        "es-es_tradnl": "es",
        "es-es@euro": "es",
        "es-eu": "es",
        "es-gb": "es",
        "es-gt": "es",
        "es-hn": "es",
        "es-la": "es",
        "es-mx": "es",
        "es-pa": "es",
        "es-pe": "es",
        "es-pr": "es",
        "es-py": "es",
        "es-sv": "es",
        "es-us": "es",
        "es-uy": "es",
        "es-ve": "es",
        "es-xl": "es",
        "et": "et",
        "et-ee": "et",
        "eu": "eu",
        "fa": "fa",
        "fa-af": "fa",
        "fa-fa":"fa",
        "fa-iq": "fa",
        "fa-ir": "fa",
        "fi": "fi",
        "fi-fi": "fi",
        "fi-fi@euro": "fi",
        "fil": "fil",
        "fil-ph": "fil",
        "fo": "fo",
        "fo-fo": "fo",
        "fr": "fr",
        "fr_fr": "fr",
        "fr-be": "fr",
        "fr-ca": "fr",
        "fr-ch": "fr",
        "fr-cn": "fr",
        "fr-dz": "fr",
        "fr-fr": "fr",
        "fr-fr;q=0.8": "fr",
        "fr-fr.utf-8": "fr",
        "fr-fr@euro": "fr",
        "fr-lu": "fr",
        "fr-ma": "fr",
        "fr-mc": "fr",
        "fr-mg": "fr",
        "fr-pt": "fr",
        "fr-re": "fr",
        "fr-tn": "fr",
        "fr-us": "fr",
        "french-france": "fr",
        "fy": "fy",
        "fy-nl": "fy",
        "ga-ie": "ga",
        "gb-gb": "gb",
        "gd": "gd",
        "gd-gb": "gd",
        "gl": "gl",
        "gl-es": "gl",
        "gl-gl": "gl",
        "gn": "gn",
        "gu": "gu",
        "gu-in": "gu",
        "ha": "ha",
        "he": "he",
        "he-il": "he",
        "hi": "hi",
        "hi-in": "hi",
        "hr": "hr",
        "hr-ba": "hr",
        "hr-hr": "hr",
        "hr-hr-hr-hr": "hr",
        "hu": "hu",
        "hu-hu": "hu",
        "hy": "hy",
        "hy-am": "hy",
        "id": "id",
        "id-": "id",
        "id-id": "id",
        "id-in": "id",
        "id-jp": "id",
        "ie": "ie",
        "ig": "ig",
        "in-id": "in",
        "is": "in",
        "is-is": "is",
        "it": "it",
        "it-ch": "it",
        "it-it": "it",
        "it-sm": "it",
        "ja": "ja",
        "ja-jp": "ja",
        "ja-jp-mac": "ja",
        "japanese-japan": "ja",
        "jp": "ja",
        "jp-jp": "ja",
        "jv": "jv",
        "jw": "jw",
        "jw-jw": "jw",
        "ka": "ka",
        "ka-ge": "ka",
        "kk": "kk",
        "kk-kz": "kk",
        "km": "km",
        "kn": "kn",
        "ko": "ko",
        "ko-kp": "ko",
        "ko-kr": "ko",
        "ku": "ku",
        "ky": "ky",
        "kz": "kz",
        "la": "la",
        "la-001": "la",
        "lb": "lb",
        "lb-lu": "lb",
        "lo": "lo",
        "lt": "lt",
        "lt-lt": "lt",
        "lv": "lv",
        "lv-lv": "lv",
        "mi": "mi",
        "mk": "mk",
        "mk-mk": "mk",
        "ml": "ml",
        "mn": "mn",
        "mr": "mr",
        "mr-in": "mr",
        "ms": "ms",
        "ms-my": "ms",
        "mua": "mua",
        "my": "my",
        "my-mm": "my",
        "nb": "nb",
        "nb-no": "nb",
        "nb-sj": "nb",
        "ne": "ne",
        "nl": "nl",
        "nl-be": "nl",
        "nl-cw": "nl",
        "nl-gb": "nl",
        "nl-nl": "nl",
        "nn": "nn",
        "nn-no": "nn",
        "no": "no",
        "nv-no": "nv",
        "or": "or",
        "pl": "pl",
        "pl-en":  "pl",
        "pl-ie": "pl",
        "pl-pl": "pl",
        "pl-pl.utf8": "pl",
        "pl-us": "pl",
        "polish-poland": "pl",
        "pt": "pl",
        "pt-br": "pt",
        "pt-en": "pt",
        "pt-pt": "pt",
        "rm": "rm",
        "rn": "rn",
        "ro": "ro",
        "ro-ro": "ro",
        "ru": "ru",
        "ru-": "ru",
        "ru-by": "ru",
        "ru-en": "ru",
        "ru-kz": "ru",
        "ru-md": "ru",
        "ru-ru": "ru",
        "ru-ua": "ru",
        "ru-us": "ru",
        "russian-russia": "ru",
        "russian(ru)": "ru",
        "se-se": "se",
        "sg": "sg",
        "sh": "sh",
        "si": "si",
        "si-si": "si",
        "sk": "sk",
        "sk-en": "sk",
        "sk-sk": "sk",
        "sl": "sl",
        "sl-si": "sl",
        "sl-sl": "sl",
        "slo-us": "sl",
        "sn": "sn",
        "spanish-chile":  "es",
        "spanish-mexico": "es",
        "sq": "sq",
        "sq-al": "sq",
        "sq-xk": "sq",
        "sr": "sr",
        "sr-cs": "sr",
        "sr-cyrl-cs":"sr",
        "sr-cyrl-rs": "sr",
        "sr-en": "sr",
        "sr-latn-cs": "sr",
        "sr-latn-rs": "sr",
        "sr-rs": "sr",
        "sv": "sv",
        "sv-fi": "sv",
        "sv-se": "sv",
        "sw": "sw",
        "ta": "ta",
        "ta-in": "ta",
        "te": "te",
        "tg": "tg",
        "th": "th",
        "th-th": "th",
        "ti": "ti",
        "tk": "tk",
        "tl": "tl",
        "tlh": "tlh",
        "tn": "tn",
        "to": "to",
        "tr": "tr",
        "tr-": "tr",
        "tr-tr": "tr",
        "tt-ru": "tt",
        "tw": "tw",
        "uk": "uk",
        "uk-ua": "uk",
        "ur": "ur",
        "ur-pk": "ur",
        "us": "en",
        "us-en": "en",
        "uz":  "uz",
        "uz-uz": "uz",
        "uzbek(uz)": "uz",
        "vi": "vi",
        "vi-us": "vi",
        "vi-vn": "vi",
        "vo": "vo",
        "zh": "zh",
        "zh-cn": "zh",
        "zh-hans-cn": "zh",
        "zh-hans-hk": "zh",
        "zh-hk": "zh",
        "zh-sg": "zh",
        "zh-tw": "zh-tw"
    ]

    func mapLanguage(_ languageCode: String) -> String {
        if let mapped = self.languageMap[languageCode.lowercased()] {
            return mapped
        }
        return languageCode
    }

    private func printLocaleIdentifiers() {
        let locales = Locale.availableIdentifiers
        
        for locale in locales {
            debugPrint("Locale => \(locale)")
        }
    }
}
